title = "DEBS2020"
baseURL = "https://debs20test.github.io/"
languageCode = "en-us"
theme = "debs20test-hugo-theme"

# The site's parameters
[params]

  # Google Analitycs
  googleAnalitycsID = "Your ID"
  description = "DEBS2020"
  author = "Sardar"

  # follow us link
  [[params.follow]]
    icon = "fa-twitter"
    URL = "https://twitter.com/ACM_DEBS"

  [[params.follow]]
    icon = "fa-facebook"
    URL = "https://www.facebook.com/ACM.DEBS"

  [[params.follow]]
    icon = "fa-linkedin"
    URL = "https://www.linkedin.com/groups/4747505/"


  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# Multilangual : FR / EN
[Languages]

  ######## english language
  [Languages.en]
  languageName = "En"
    weight = 2
    languageCode = "en-us"
    title = "DEBS 2020"
    dateFormat = "January 2, 2006"
    home = "HOME"


  [Languages.en.menu]

    [[Languages.en.menu.header]]
    weight = 2
    name = "CALLS"
    hasChildren = true

      [[Languages.en.menu.header]]
      weight = 1
      name = "Call for Research Papers"
      parent = "CALLS"
      url = ""

      [[Languages.en.menu.header]]
      weight = 2
      name = "Call for Industry Papers"
      parent = "CALLS"
      url = ""

      [[Languages.en.menu.header]]
      weight = 2
      name = "Call for Tutorials"
      parent = "CALLS"
      url = "/callfortutorials"

      [[Languages.en.menu.header]]
      weight = 3
      name = "Call for Grand Challenge Solutions"
      parent = "CALLS"
      url = "/callforgrandchallengesolutions"

      [[Languages.en.menu.header]]
      weight = 4
      name = "Call for Posters and Demos"
      parent = "CALLS"
      url = ""

      [[Languages.en.menu.header]]
      weight = 5
      name = "Call for Doctoral Symposium"
      parent = "CALLS"
      url = ""

    [[Languages.en.menu.header]]
    weight = 3
    name = "COMMITTEE"
    hasChildren = true

        [[Languages.en.menu.header]]
        weight = 1
        name = "Organizing Committee"
        parent = "COMMITTEE"
        url = "/organizingcommittee"

        [[Languages.en.menu.header]]
        weight = 2
        name = "Program Committee"
        parent = "COMMITTEE"
        url = ""

    [[Languages.en.menu.header]]
    weight = 4
    name = "CONFERENCE INFO"
    hasChildren = true

      [[Languages.en.menu.header]]
      weight = 1
      name = "Important Dates"
      parent = "CONFERENCE INFO"
      url = ""

      [[Languages.en.menu.header]]
      weight = 2
      name = "Venue Information"
      parent = "CONFERENCE INFO"
      url = "/venueinformation"

      [[Languages.en.menu.header]]
      weight = 3
      name = "Past DEBS Events"
      parent = "CONFERENCE INFO"
      url = "/pastdebsevents"

      [[Languages.en.menu.header]]
      weight = 4
      name = "Accommodation"
      parent = "CONFERENCE INFO"
      url = "/accommodation"

      [[Languages.en.menu.header]]
      weight = 5
      name = "Visa Information"
      parent = "CONFERENCE INFO"
      url = "/visainformation"

    [[Languages.en.menu.header]]
    weight = 5
    name = "PROGRAM"
    hasChildren = true

      [[Languages.en.menu.header]]
      weight = 1
      name = "Full Program"
      parent = "PROGRAM"
      url = ""

      [[Languages.en.menu.header]]
      weight = 2
      name = "Keynote Speakers"
      parent = "PROGRAM"
      url = ""

    [[Languages.en.menu.header]]
    weight = 6
    name = "REGISTRATION"
    hasChildren = true

      [[Languages.en.menu.header]]
      weight = 1
      name = "Conference Registration"
      parent = "REGISTRATION"
      url = ""

      [[Languages.en.menu.header]]
      weight = 2
      name = "Camera-Ready Instructions"
      parent = "REGISTRATION"
      url = ""

      [[Languages.en.menu.header]]
      weight = 3
      name = "Travel Grants"
      parent = "REGISTRATION"
      url = ""

    [[Languages.en.menu.header]]
    weight = 7
    name = "SUPPORT DEBS 2020"
    hasChildren = false
    url = "/support"

    #[[Languages.en.menu.footer]]
      #weight = 1
      #name = "About us"
      #url = "#"
    #[[Languages.en.menu.footer]]
      #weight = 2
      #name = "Contact us"
      #url = "#"
    #[[Languages.en.menu.footer]]
      #weight = 3
      #name = "How it works"
      #url = "#"
    #[[Languages.en.menu.footer]]
      #weight = 4
      #name = "Blog"
      #url = "#"
    #[[Languages.en.menu.footer]]
      #weight = 5
      #name = "Terms"
      #url = "#"

  [Languages.en.params.slider]
    enable = true
    title = "DEBS 2020"
    subtitle = "14TH ACM INTERNATIONAL CONFERENCE ON DISTRIBUTED AND EVENT-BASED SYSTEMS"
    date = "13th - 17th July 2020"
    place = "Montreal, Quebec, Canada"
    bgImage = "img/Montreal.jpg"
    bgImageAlt = "img/Montreal.jpg"
    btnText = "Conference Information"
    url = "#scope"

  [Languages.en.params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "About DEBS"
    text1 = "Over the past decade, the ACM International Conference on Distributed and Event‐based Systems (DEBS) has become the premier venue for cutting-edge research in the field of event processing and distributed computing, and the integration of distributed and event-based systems in relevant domains such as Big Data, AI/ML, IoT, and Blockchain. The objectives of the ACM International Conference on Distributed and Event‐Based Systems (DEBS) are to provide a forum dedicated to the dissemination of original research, the discussion of practical insights, and the reporting of experiences relevant to distributed systems and event‐based computing. The conference aims at providing a forum for academia and industry to exchange ideas through its tutorials, research papers, and the Grand Challenge."

  [Languages.en.params.blog1]
    enable = true
    text1Title = "Models, architectures and paradigms:"
    text2Title = "Systems and software:"
    text3Title = "Applications:"
    title = "TOPICS OF INTEREST"
    text1 = " Event-driven architectures, real-time analytics, complex event processing, event processing for AI/ML, event processing in big and fast data, publish/subscribe, data stream processing, security and encryption in stream processing, rule-based systems, maintenance of materialized views, dynamic graph processing, in-network processing, logic-based event recognition, event correlation and pattern languages."
    text2 = " Distributed data processing, distributed programming, federated event-based systems, smart contracts, blockchain and distributed ledger technologies, message queues, middleware, AI/ML for event processing, information-centric networking, software-defined networking, security, reliability and resilience, programmable hardware, energy management and green computing as well as cloud, fog, ubiquitous and mobile computing."
    text3 = " Use cases, requirements and applications of distributed and event-based systems in various domains including Internet-of-Things, cyber-physical systems, sensor networks, social networking, multimedia analytics, finance, healthcare and logistics, computer and network security. Also, relevant topics span enterprise-level computing, including enterprise application integration, real-time enterprises, event-based business process management, and support for enterprises to respond in timely fashion to changing situations."

  [Languages.en.params.venue]
    enable = true
    title = "venue"
    italic = "DEBS 2020 will be hosted at pavilion E, École de technologie supérieure in Montreal, QC, Canada."

  [Languages.en.params.organizers]
    enable = true
    title = "General Co-Chairs"
    text1 = "Kaiwen Zhang, ÉTS Montréal"
    text2 = "Khuzaima Daudjee, University of Waterloo"
    text3 = "Bettina Kemme, McGill University"

  [Languages.en.params.feature]
    enable = true
    title = "École de technologie supérieure"
    bgImage = "img/campus.png"
    bgImageAlt = "img/campus.png"
    content = "The conference venue will be the École de technologie supérieure (ÉTS). Specializing in education and applied research in engineering and technology transfer to companies, ÉTS trains engineers and researchers who stand apart because of their practical and innovative approach. We offer approximately 100 different study programs for undergraduate, graduate and doctoral students in five departments."
    [Languages.en.params.feature.button]
      caption = "Venue Information"
      url = "/venueinformation"

  [Languages.en.params.call]
    enable = false
    #bgImage = "img/call-to-action-bg.jpg"
    #title = "We design delightful digital experiences."
    #paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
    #[Languages.en.params.call.button]
      #url = "#"
      #text = "tell us your story"
